var searchData=
[
  ['kdtreeindex',['KDTreeIndex',['../classtrees_1_1_k_d_tree_index.html',1,'trees::KDTreeIndex&lt; ElementType &gt;'],['../classtrees_1_1_k_d_tree_index.html#abfde9fe47fe77c9fdde1af8d500b85e5',1,'trees::KDTreeIndex::KDTreeIndex()']]],
  ['kdtreeindexparams',['KDTreeIndexParams',['../structtrees_1_1_k_d_tree_index_params.html',1,'trees::KDTreeIndexParams'],['../structtrees_1_1_k_d_tree_index_params.html#a4a1c6e02700c365e787d09fb4b821553',1,'trees::KDTreeIndexParams::KDTreeIndexParams()']]],
  ['knnradiusresultset',['KNNRadiusResultSet',['../classtrees_1_1_k_n_n_radius_result_set.html',1,'trees']]],
  ['knnradiusuniqueresultset',['KNNRadiusUniqueResultSet',['../classtrees_1_1_k_n_n_radius_unique_result_set.html',1,'trees::KNNRadiusUniqueResultSet&lt; DistanceType &gt;'],['../classtrees_1_1_k_n_n_radius_unique_result_set.html#ab20dd750c139d441ab3d715a4b4f1bac',1,'trees::KNNRadiusUniqueResultSet::KNNRadiusUniqueResultSet()']]],
  ['knnresultset',['KNNResultSet',['../classtrees_1_1_k_n_n_result_set.html',1,'trees']]],
  ['knnresultset2',['KNNResultSet2',['../classtrees_1_1_k_n_n_result_set2.html',1,'trees']]],
  ['knnsearch',['knnSearch',['../classtrees_1_1_n_n_index.html#abf4572754ebd83300ab7c7747be10752',1,'trees::NNIndex::knnSearch(const Matrix&lt; ElementType &gt; &amp;queries_, Matrix&lt; size_t &gt; &amp;indices_, Matrix&lt; ElementType &gt; &amp;dists_, size_t knn_, const TreeParams &amp;params_)'],['../classtrees_1_1_n_n_index.html#a4f489d7dd35c009a8e1e246dc569f8a0',1,'trees::NNIndex::knnSearch(const Matrix&lt; ElementType &gt; &amp;queries_, Matrix&lt; int &gt; &amp;indices_, Matrix&lt; ElementType &gt; &amp;dists_, size_t knn_, const TreeParams &amp;params_)'],['../classtrees_1_1_index.html#a716c861946ed217622a9cfc60d25196f',1,'trees::Index::knnSearch(const Matrix&lt; ElementType &gt; &amp;queries_, Matrix&lt; size_t &gt; &amp;indices_, Matrix&lt; ElementType &gt; &amp;dists_, size_t knn_, const TreeParams &amp;params_)'],['../classtrees_1_1_index.html#a50aa3029ca0fc9eb3d2bb4c5d0f8e71a',1,'trees::Index::knnSearch(const Matrix&lt; ElementType &gt; &amp;queries_, Matrix&lt; int &gt; &amp;indices_, Matrix&lt; ElementType &gt; &amp;dists_, size_t knn_, const TreeParams &amp;params_)']]],
  ['knnsearchthreadpool',['knnSearchThreadpool',['../classtrees_1_1_n_n_index.html#a059a92d41b77db12a7803e8348ae1c11',1,'trees::NNIndex']]],
  ['knnsimpleresultset',['KNNSimpleResultSet',['../classtrees_1_1_k_n_n_simple_result_set.html',1,'trees']]],
  ['knnuniqueresultset',['KNNUniqueResultSet',['../classtrees_1_1_k_n_n_unique_result_set.html',1,'trees::KNNUniqueResultSet&lt; DistanceType &gt;'],['../classtrees_1_1_k_n_n_unique_result_set.html#a97620bc6b7febbe8c1885e7191fadf86',1,'trees::KNNUniqueResultSet::KNNUniqueResultSet()']]]
];
